[config]
reload_apps = true
reload_apps_signal = 1

[templates.waybar]
input_path = './templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

# Swaync
[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

# Swaync
[templates.swayosd]
input_path = '~/.config/matugen/templates/swayosd-colors.css'
output_path = '~/.config/swayosd/colors.css'
post_hook = 'pkill swayosd-server;setsid -f swayosd-server >/dev/null 2>&1'

# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/themes/colors.rasi'
