bc
bison
bzip2
ca-certificates
ccache
clang
cmake
cpio
curl
diffutils
docker
elfutils
expat
flex
gawk
gcc
gmp
gnupg
gzip
libarchive
libcap
libcap-ng
libmpc
libpcap
libvirt
libzip
lld
llvm
lz4
lzip
lzop
make
mpfr
ncurses
openssl
patch
patchelf
pkgconf
qemu
rsync
subversion
tar
unzip
virt-install
virt-manager
virt-viewer
wget
xz
zip
fd
neovim
nodejs
npm
python-pip
stow
tree-sitter
zsh
bluez
grim
gtk4-layer-shell
inotify-tools
libadwaita
pipewire-jack
polkit
qt6-base
qt6-wayland
rofi
slurp
swaybg
swaylock
swayidle
waybar
wl-clipboard
wlsunset
xdg-dbus-proxy
xdg-desktop-portal
xdg-desktop-portal-gtk
xdg-desktop-portal-wlr
xdg-user-dirs
xdg-utils
gnome-calculator
gnome-calendar
gnome-clocks
gnome-keyring
gnome-system-monitor
gnome-text-editor
noto-fonts-emoji
kdeconnect
libva-utils
loupe
nautilus
ffmpegthumbnailer
fuse
playerctl
yad
gvfs-mtp
libmtp
xorg-xwayland
android-tools
brightnessctl
trash-cli
git-delta
cliphist
swww
matugen
ghostty
libnotify
xdg-desktop-portal-gnome
nm-connection-editor
network-manager-applet
blueman
xwayland-satellite
github-cli
nautilus-python
libnautilus-extension
sushi
nautilus-image-converter
tree
tree-sitter-cli
rofi-emoji
python-uv
mpv
auto-cpufreq
rofimoji
polkit-gnome
