# Swaylock color variables generated by matugen

key_hl_color="{{ colors.primary.default.hex }}f2"
ring_color="{{ colors.primary.default.hex }}f2"
text_color="{{ colors.on_surface.default.hex }}e6"

inside_clear_color="{{ colors.surface.default.hex }}f2"
ring_clear_color="{{ colors.primary.default.hex }}f2"
text_clear_color="{{ colors.on_surface.default.hex }}e6"

inside_ver_color="{{ colors.surface.default.hex }}f2"
ring_ver_color="{{ colors.primary.default.hex }}f2"
text_ver_color="{{ colors.on_surface.default.hex }}e6"

bs_hl_color="{{ colors.surface_container.default.hex }}ff"

inside_wrong_color="{{ colors.error.default.hex }}ff"
ring_wrong_color="{{ colors.error.default.hex }}ff"
text_wrong_color="{{ colors.on_error.default.hex }}ff"
